image_directory: 147091 # Test files [86016, 118035, 147091, 176035, 176039, 353013]
verbose: true # Whether or not to print stuff
max_generation: 20
population_size: 50
stop_threshold: 0.75 # Stop the genetic algorithm when if we reach this fitness
crossover_probability: 0.7
mutation_probability: 0.2
tournament_size: 2 # How many parents should compete in the tournament for
# which parent should get to breed. Officialy, NSGA-II uses a binary tournament.
lower_segmentation_count_limit: 1
upper_segmentation_count_limit: 50
# Ratio of how many of the best parents should be brought into the next
# generation regardless of generation number.
sga_elitism: 0.01
