image_directory: 86016

population_size: 100
max_generation: 100

# Stop the genetic algorithm when if we reach this fitness
stop_threshold: 0.0

crossover_probability: 0.7

# The probability of applying mutation
mutation_probability: 0.2

# How many parents should compete in the tournament for which parent should get to breed
# Officialy, NSGA-II uses a binary tournament
tournament_size: 2

# Ratio of how many of the best parents should be brought into the next
# generation regardless of generation number. This only applies to the SGA.
sga_elitism: 0.01

verbose: true

# How often to save the best found solution to a file
save_interval: 5000
