input_file: my_problem

population_size: 1600
max_generation: 30000

# Stop the genetic algorithm when if we reach this fitness
stop_threshold: 6520.5

# Ratio of how many of the best parents should be brought into the next
# generation regardless of generation number.
elite_ratio: 0.01

crossover_chance: 0.6

bound: 2.0

# Typically between 0.6 and 1.0. Represents the probability that we select the best
# individual and not a random one.
tournament_selection_number: 0.7

# The probability that we choose the best feasible location over the first location
crossover_insertion_number: 0.8

# The probability of applying mutation
intra_depot_mutation_rate: 0.25
inter_depot_mutation_rate: 0.30

# Do inter-depot mutation (instead of intra-depot) every APPRATE generation
APPRATE: 10

verbose: true

# How often to save the best found solution to a file
save_interval: 5000
