input_file: p01

population_size: 10000
max_generation: 200

# Ratio of how many of the best parents should be brought into the next
# generation regardless of generation number.
elite_ratio: 0.01

crossover_chance: 0.7

bound: 2.0

# Typically between 0.6 and 1.0. Represents the probability that we select the best
# individual and not a random one.
tournament_selection_number: 0.8

# The probability that we choose the best feasible location over the first location
crossover_insertion_number: 1.0

# Do inter-depot mutation (instead of intra-depot) every APPRATE generation
APPRATE: 10
